### ISSUE TITLE
Problem with running Integration.py (SOLVED)

### ISSUE THREAD

**Issue by mduranb** [lapig-ufg/PPTs#1]
Dear friend, I need as part of a project get daily rainfall for hours and found your files developed and want to run the integration file gives me the following error:
Problem with running Integration.py, line 30, in <module>
From calibrate_gpm_day import calibrate_gpm_day
ModuleNotFoundError: No module named 'calibrate_gpm_day'

**Comment by vieiramesquita** [comment]
Hi mduranb, sorry for the problem. I will update this code until the weekend because I've build a new algorithm that is more faster and more user-friendly.

**Comment by mduranb** [comment]
Thank you, Muito obrigado, Muchas Gracias.
Desde Chile

**Comment by mduranb** [comment]
Dear Friend, diculpa somewhat my insistence, but you will have updated the code of integration.py
Greetings from Chile

**Comment by mduranb** [comment]
Dear Friend, excuse me somewhat for my insistence, but you will have updated the integration.py code
Greetings from Chile

**Comment by vieiramesquita** [comment]
Hi mduranb. I've updated the source code and the readme, check out.
